[package]
name = "uld"
version = "0.1.0"
edition = "2021"

[dependencies]
object = { version = "0.36.0", default-features = false, features = ["read_core", "write_std", "elf", "std"] }
memmap2 = "0.9"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
